### ISSUE TITLE
support for Nexus 9

### ISSUE THREAD

**Issue by roelvandun** [Commit451/NativeStackBlur#2]
When I try to run my app on Nexus 9 with NativeStackBlur dependency, I get the following exception:

UNCAUGHT EXCEPTION (main). Force logging out.: 
                                                                              java.lang.Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/BLA.dev-2/base.apk"],nativeLibraryDirectories=[/data/app/BLA.dev-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "library.so"
...
                                                                               Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/BLA.dev-2/base.apk"],nativeLibraryDirectories=[/data/app/BLA.dev-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "library.so"
...

The app does work on other (non 64-bit) devices.

**Comment by Jawnnypoo** [comment]
Looks like it is an arm64-v8a architecture. Are you using the latest version of the library? 1.0.2?

**Comment by roelvandun** [comment]
Yes, I use 1.0.2 (compile 'com.commit451:NativeStackBlur:1.0.2')

The library.so that is mentioned in the exception is a native library from our project, not from your library. But the exception only occurs on 64-bit devices and only if I use this library. I managed to have a work around with http://stackoverflow.com/questions/30782848/how-to-use-32-bit-native-libaries-on-64-bit-android-device
But I don't know if that is a proper fix

**Comment by Jawnnypoo** [comment]
Can you do me a favor and run the sample project in this repo and see if that will run okay?

**Comment by roelvandun** [comment]
The sample project runs okay on a Nexus 9.
I then presume it must be some kind of exception that occurs when more native libraries are combined in some way.

**Comment by Jawnnypoo** [comment]
Going to go ahead and close this then since it sounds like it may not be related to this project
