### ISSUE TITLE
Build failing - can't find NativeStackBlur-1.0.5.aar

### ISSUE THREAD

**Issue by adamvietnam** [Commit451/NativeStackBlur#8]
Hi,

I've been happily using NativeStackBlur-1.0.5.aar in a project for a quite a few years now (Thanks!)

I've just gone to clean build the project today and am getting the following
<code>
Could not find NativeStackBlur-1.0.5.aar (com.github.Commit451:NativeStackBlur:1.0.5).
        Searched in the following locations:
            https://jitpack.io/com/github/Commit451/NativeStackBlur/1.0.5/NativeStackBlur-1.0.5.aar
</code>

That link gives an error:

<code>
Build failed. See the log at jitpack.io
</code>

Any ideas?

**Comment by Jawnnypoo** [comment]
Interesting. 1.0.4 should work fine if you just want to use that one instead.

**Comment by adamvietnam** [comment]
Thanks for coming back to me.

In the end I incorporated the source direct from :

https://github.com/kikoso/android-stackblur

as per the instructions here but i'll give that a go too.

Cheers

**Comment by Jawnnypoo** [comment]
Whatever works for you is great! Thanks

**Comment by Jawnnypoo** [comment]
I went ahead and released 1.0.7 as well if you want to give that a try

**Comment by adamvietnam** [comment]
Awesome, thanks!

**Comment by adamvietnam** [comment]
I can confirm 1.0.7 builds and works fine - thanks again.
